package dev.chardoncs.ezmpv.ui.theme

import androidx.compose.ui.graphics.Color

// Brand seed color (M3 reference purple). Dynamic color on Android 12+ overrides these.
val BrandSeed = Color(0xFF6750A4)

// Light scheme tonal stops (fallback below Android 12).
val LightPrimary = Color(0xFF65558F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE9DEFF)
val LightOnPrimaryContainer = Color(0xFF20104A)
val LightSecondary = Color(0xFF615B71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE7DEF8)
val LightOnSecondaryContainer = Color(0xFF1D192B)
val LightTertiary = Color(0xFF7D5260)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD9E2)
val LightOnTertiaryContainer = Color(0xFF31101D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFEF7FF)
val LightOnBackground = Color(0xFF1D1B20)
val LightSurface = Color(0xFFFEF7FF)
val LightOnSurface = Color(0xFF1D1B20)
val LightSurfaceVariant = Color(0xFFE7E0EB)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightOutline = Color(0xFF7A757F)
val LightOutlineVariant = Color(0xFFCAC4CF)

// Dark scheme tonal stops.
val DarkPrimary = Color(0xFFCFBCFF)
val DarkOnPrimary = Color(0xFF36275D)
val DarkPrimaryContainer = Color(0xFF4D3D75)
val DarkOnPrimaryContainer = Color(0xFFE9DEFF)
val DarkSecondary = Color(0xFFCBC2DB)
val DarkOnSecondary = Color(0xFF332D41)
val DarkSecondaryContainer = Color(0xFF494455)
val DarkOnSecondaryContainer = Color(0xFFE7DEF8)
val DarkTertiary = Color(0xFFEFB8C8)
val DarkOnTertiary = Color(0xFF492532)
val DarkTertiaryContainer = Color(0xFF633B48)
val DarkOnTertiaryContainer = Color(0xFFFFD9E2)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF141218)
val DarkOnBackground = Color(0xFFE6E0E9)
val DarkSurface = Color(0xFF141218)
val DarkOnSurface = Color(0xFFE6E0E9)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4CF)
val DarkOutline = Color(0xFF948F99)
val DarkOutlineVariant = Color(0xFF49454F)